yarnPath: .yarn/releases/yarn-2.3.3.cjs
#packageExtensions:
#  merge-anything@4.0.x:
#    dependencies:
#      ts-toolbelt: 8.0.x
#  merge-anything@3.0.x: # merge-anything is brittle, probably get away from it in the future
#    dependencies:
#      ts-toolbelt: 6.12.x
