yarnPath: .yarn/releases/yarn-2.3.3.cjs
packageExtensions:
  jest@*:
    dependencies:
      fsevents: 2.1.x
#  merge-anything@4.0.x:
#    dependencies:
#      ts-toolbelt: 8.0.x
#  merge-anything@3.0.x:
#    dependencies:
#      ts-toolbelt: 6.12.x
